server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    gzip on;
    gzip_types text/plain text/css application/javascript application/json image/svg+xml;

    location /MEM-AIVisdefect/ {
        try_files $uri $uri/ /MEM-AIVisdefect/index.html;
    }

    location /detector-ui/ {
        try_files $uri $uri/ /detector-ui/index.html;
    }

    location = / {
        return 302 /MEM-AIVisdefect/;
    }
}
